version: '2'
services:
  redis:
    image: "hub.juniper.net/contrail/contrail-external-redis:1912.32"
    env_file: /etc/contrail/redis.env
    network_mode: "host"
    restart: always
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "20m"
